import datetime
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, LargeBinary
from sqlalchemy.orm import relationship
from app.storage.database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)
    is_enrolled = Column(Boolean, default=False)
    model_type = Column(String, default="LogisticRegression")
    
    # Binary field storing the serialized trained classifier pipeline (joblib/pickle)
    model_binary = Column(LargeBinary, nullable=True)
    
    # Tuned thresholds for this specific user
    threshold_balanced = Column(Float, default=0.5)
    threshold_high_security = Column(Float, default=0.7)
    threshold_low_friction = Column(Float, default=0.3)
    
    # Active operational profile ('balanced', 'high_security', 'low_friction')
    active_profile = Column(String, default="balanced")
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationships
    enrollment_samples = relationship("EnrollmentSample", back_populates="user", cascade="all, delete-orphan")
    session_logs = relationship("SessionLog", back_populates="user", cascade="all, delete-orphan")


class EnrollmentSample(Base):
    __tablename__ = "enrollment_samples"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    # Extracted keystroke features
    mean_dwell_time = Column(Float, nullable=False)
    std_dwell_time = Column(Float, nullable=False)
    mean_flight_time = Column(Float, nullable=False)
    typing_speed = Column(Float, nullable=False)
    backspace_rate = Column(Float, nullable=False)
    pause_frequency = Column(Integer, nullable=False)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationship
    user = relationship("User", back_populates="enrollment_samples")


class SessionLog(Base):
    __tablename__ = "session_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    
    # Score generated by classifier (probability of genuine, 0.0 to 1.0)
    score = Column(Float, nullable=False)
    # Threshold applied at the time of evaluation
    applied_threshold = Column(Float, nullable=False)
    # Active profile at time of evaluation
    applied_profile = Column(String, nullable=False)
    # True if score < threshold (anomalous session / potential hijack)
    is_anomalous = Column(Boolean, default=False)
    
    keystroke_count = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationship
    user = relationship("User", back_populates="session_logs")
